---
title: "dataviz"
author: "Neha Moopen"
date: 
output: rmdformats::material
---

from: https://www.data-to-viz.com/

- see also: https://datavizproject.com/

- for tables: https://rfortherestofus.com/2019/11/how-to-make-beautiful-tables-in-r/

# BAR PLOT

already tried out

# LOLLIPOP

```{r}
lollipopplot <-
  dppsurvey %>% 
pivot_longer(cols = grep("Faculty_[0-9]$", names(dppsurvey), value=TRUE), 
               values_drop_na = TRUE,
               values_to = "Faculty") %>%
  select(-name) %>%
  group_by(Faculty) %>%
  summarise(Count = length(Faculty)) %>%
  arrange(Count) %>% # Order by count
  mutate(Faculty = factor(Faculty, levels=Faculty)) %>%
# Update factor levels
  ggplot(aes(x = Faculty, y = Count)) +
  geom_point(stat = "identity") +
  geom_segment( aes(x= Faculty, xend=Faculty, y=0, yend=Count)) +
  labs(x = "", title = "Faculties",
       caption = "UU faculty representation in the Data Privacy Survey") +
  coord_flip() +
  theme_classic() +
  geom_label(aes(label = Count), position=position_dodge(width=1.2),
             color = "black",
             fill = "#FFCD00")

print(lollipopplot)

# ggplot(dppsurvey, aes(x=x, y=y)) +
# geom_point() + 
# geom_segment( aes(x=x, xend=x, y=0, yend=y))

```

# WAFFLE

seems a bit too much for the current dataset

# WORD CLOUD

not relevant yet

# DONUT



# PIE



# TREEMAP

```{r}
# library
# library(treemap)
 
# Create data
group <- c("group-1","group-2","group-3")
value <- c(13,5,22)
data <- data.frame(group,value)
 
# treemap
treemap <- treemap(data,
            index="group",
            vSize="value",
            type="index"
            )

print(treemap)

```

```{r}
treemap_data <- dppsurvey %>% 
  pivot_longer(cols = grep("Faculty_[0-9]$", names(dppsurvey), value=TRUE), 
               values_drop_na = TRUE,
               values_to = "Faculty") %>%
  select(-name) %>%
  group_by(Faculty) %>%
  summarise(Count = length(Faculty)) %>%
  arrange(Count) %>% # Order by count
  mutate(Faculty = factor(Faculty, levels=Faculty)) 

treemap_faculty <- treemap(treemap_data,
                           index="Faculty",
                           vSize="Count",
                           type="index")

```

```{r}
group <- c(rep("group-1",4),rep("group-2",2),rep("group-3",3))
subgroup <- paste("subgroup" , c(1,2,3,4,1,2,1,2,3), sep="-")
value <- c(13,5,22,12,11,7,3,1,23)
data <- data.frame(group,subgroup,value)

treemap(data,
            index=c("group","subgroup"),
            vSize="value",
            type="index"
            ) 

```

```{r}
dt <- dppsurvey %>%
  select(starts_with("Faculty"), starts_with("Position")) %>%
   pivot_longer(cols = grep("Faculty_[0-9]$", names(dppsurvey), value=TRUE), 
               values_drop_na = TRUE,
               values_to = "Faculty") %>%
  select(-name) %>%
   pivot_longer(cols = grep("Position_[0-9]$", names(dppsurvey), value=TRUE), 
               values_drop_na = TRUE,
               values_to = "Position") %>%
  select(-name) %>%
  select(-Faculty_99, -Position_7_TEXT)

dt2 <- dt %>% group_by(Faculty, Position) %>% summarise(Count = length(Position))

```


```{r}
treemap_subgroup_data <- treemap(dt2,
            index=c("Faculty","Position"),
            vSize = "Count",
            type="index"
            )

print(treemap_subgroup_data)
```


# CIRCULAR PACKING
 


